import type { WineEntry } from './wine-entry';
import { localISODate } from './calendar';

export function createEntry(id: string, now: Date = new Date()): WineEntry {
  const timestamp = now.getTime();
  const dateStr = localISODate(now);

  return {
    id,
    schemaVersion: 3,
    revision: 0,
    produtor: '',
    vinho: '',
    safra: '',
    uvas: '',
    regiaoPais: '',
    tipo: null,
    estilo: null,
    skinContact: false,
    subestilo: null,
    visual: {
      coreColour: null,
      intensity: null,
      clarity: null,
      brightness: null,
      rimVariation: null,
      viscosity: null,
      observations: [],
    },
    olfato: {
      condition: null,
      faults: [],
      intensity: null,
      oak: null,
      maturity: null,
      aromas: '',
    },
    paladar: {
      condition: null,
      faults: [],
      sweetness: null,
      sparkle: null,
      body: null,
      texture: [],
      acidity: null,
      flavourIntensity: null,
      oak: null,
      maturity: null,
      tanninLevel: null,
      tanninQuality: [],
      alcohol: null,
      abv: '',
      finish: null,
      aromasBoca: '',
      retrogosto: '',
    },
    conclusao: {
      avaliacaoEstrelas: null,
      impressaoFinal: '',
      harmonizacao: '',
      preco: '',
      asiQuality: null,
      ageing: null,
      vinification: [],
      climate: null,
      climateType: null,
    },
    servico: {
      temperature: null,
      glass: null,
      decant: null,
      dishStyle: null,
      pairingComponents: [],
    },
    legacyNotes: {},
    tags: [],
    dataDegustacao: dateStr,
    criadoEm: timestamp,
    atualizadoEm: timestamp,
    kind: 'personal',
    sourceFormat: 'native-v2',
    favorite: false,
    occasion: '',
    origin: {
      countryCode: null,
      region: '',
    },
    aromaTags: [],
    photoId: null,
    provenance: {},
    evidence: {
      noteAuthoredAt: null,
      aromasAuthoredAt: null,
      originConfirmedAt: null,
      revisitedAt: null,
    },
    importMetadata: {},
  };
}
